services:
  app:
    container_name: my-app-container
    build:
      context: .
    depends_on:
      - mysql_db
      - redis_db
    networks:
      - local
    ports:
      - "8080:8080"
  mysql_db:
    container_name: mysql-db
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    networks:
      - local
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump/dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump.sql
  redis_db:
    container_name: redis-db
    image: redis:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "6379:6379"
    networks:
      - local

volumes:
  mysql-data:

networks:
  local:
    driver: bridge